### ISSUE TITLE
Invalid determinism on single transition DFA on test

### ISSUE THREAD

**Issue by ZoraizQ** [Reisande/RFLAP#135]
![image](https://user-images.githubusercontent.com/45783867/105611452-4a401e80-5dd7-11eb-8a3c-6ecd157fcd6b.png)

The way determinism is evaluated, a dead state seems to be always required.
For example, the previous DFA does not work but this does. There are no transitions from q1 which is probably the source of this alert but it is still a valid theoretical DFA.

![image](https://user-images.githubusercontent.com/45783867/105611357-89ba3b00-5dd6-11eb-83f0-29743a21cd6d.png)

**Comment by Reisande** [comment]
The first dfa is expected behavior. it is non deterministic because Q1 does not have a transition for character 0. However you are right that the second dfa is incorrectly registered as deterministic due to Q0 not having a transition for 1.

**Comment by Reisande** [comment]
The issue seems to be in the outgoing packet from the POST request. Here is the corresponding json object for that automata:

![image](https://user-images.githubusercontent.com/42556808/105790888-b68f5f00-5f4a-11eb-9798-2fc7314c93ea.png)

**Comment by heldeo** [comment]
Thanks for finding this ❤️
