### ISSUE TITLE
Frontend: duplicate states

### ISSUE THREAD

**Issue by Reisande** [Reisande/RFLAP#47]
I am not sure of what the cause is, but some students have reported cases where they have created more than one state with the same name. This causes a lot of false negatives in the autograder. We have been getting around this by telling them to refresh and clear the page, but they lose all progress of their automata when they do this. They should either have the ability to rename nodes, the root cause of the bug should be found and removed, or both.

**Comment by heldeo** [comment]
Resolved, forgot PR, its ninety - something  🤷
