### ISSUE TITLE
Frontend: remove physics and allow for no conflicting transitions

### ISSUE THREAD

**Issue by Reisande** [Reisande/RFLAP#48]
The users have reported that creating automata with the physics is frustrating. When we removed the physics effects, the students could not make two nodes have transitions to each other because the transitions would overlap and be uneditable.

**Comment by heldeo** [comment]
Addressed in https://github.com/Reisande/Rflap/pull/62 . 

Would like further feedback on the generally usability of the new node/edge interactions.

**Comment by heldeo** [comment]
Addressed in https://github.com/Reisande/Rflap/pull/62 . 

Would like further feedback on the generally usability of the new node/edge interactions.
